import "./globals.css";
import Header from "./componnets/header";
import { Provider } from "react-redux";
import ReduxProvider from "./redux-provider";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Online exam",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[#cfa455c7]`}
      >
        <Header />
        <main>
         <ReduxProvider>
            {children}
          </ReduxProvider>
        </main>

      </body>
    </html>
  );
}
